spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank loans related PROD APIs"
  contactDetails:
    name: "Chris Adam - Product Owner"
    email: "chrisadam@gmail.com"
  onCallSupport:
    - (777) 777-1234